version: "3"
name: "zerotier"

services:
  zerotier:
    image: zyclonite/zerotier:latest
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - ./controller:/var/lib/zerotier-one
      - ./admin.sh:/z
      - ./init.sh:/init.sh
    ports:
      - "9993:9993/udp"
    entrypoint: [ "sh" ]
    command: [ "init.sh" ]
